import { isStyleTargetId } from "@/lib/dev/style-lab-inspect";
import type { WillardImageOverride } from "@/lib/dev/willard-assets";

export const WILLARD_GENERATED_IMAGE_FILE_RELATIVE_PATH = "app/the-feed/willard.generated.images.ts";

const GENERATED_IMAGE_HEADER = `/*
 * This file is generated by /willard from a local Apply action.
 * It is the reviewable source-of-truth override layer for feed-related image replacements.
 * Manual edits may be overwritten the next time Apply is used.
 */`;

export const SOURCE_APPLIED_IMAGE_TARGET_IDS = [
  "article-image",
  "blog-image",
  "homepage-blog-image",
  "spotlight-image",
] as const;

export type WillardSourceAppliedImageTargetId =
  (typeof SOURCE_APPLIED_IMAGE_TARGET_IDS)[number];

export type WillardGeneratedImageOverride = {
  targetId: WillardSourceAppliedImageTargetId;
  assetId: string;
  url: string;
  altText?: string;
};

export function buildGeneratedWillardImageOverridesModule(
  imageOverrides: WillardImageOverride[] = []
): string {
  const overrides = collectSourceAppliedImageOverrides(imageOverrides);
  const entries = Array.from(overrides.entries()).sort(([left], [right]) =>
    left.localeCompare(right)
  );

  const body =
    entries.length === 0
      ? "{}"
      : `{
${entries
  .map(([, override]) => buildOverrideEntry(override))
  .join(",\n")}
}`;

  return `${GENERATED_IMAGE_HEADER}

import type {
  WillardGeneratedImageOverride,
  WillardSourceAppliedImageTargetId,
} from "@/lib/dev/style-lab-images";

export const WILLARD_IMAGE_OVERRIDES: Partial<
  Record<WillardSourceAppliedImageTargetId, WillardGeneratedImageOverride>
> = ${body};
`;
}

export function summarizeSourceAppliedImageOverrides(
  imageOverrides: WillardImageOverride[] = []
): { imageSourceOverrideCount: number } {
  return {
    imageSourceOverrideCount: collectSourceAppliedImageOverrides(imageOverrides).size,
  };
}

export function collectSourceAppliedImageOverrides(
  imageOverrides: WillardImageOverride[] = []
): Map<WillardSourceAppliedImageTargetId, WillardGeneratedImageOverride> {
  const grouped = new Map<WillardSourceAppliedImageTargetId, WillardGeneratedImageOverride>();

  for (const item of imageOverrides) {
    if (!item || !isSourceAppliedImageTargetId(item.targetId) || !isStyleTargetId(item.targetId)) {
      continue;
    }

    const url = normalizeModuleString(item.url ?? "");
    const assetId = normalizeModuleString(item.assetId ?? "");
    const altText = normalizeModuleString(item.altText ?? "");
    if (!url || !assetId) {
      continue;
    }

    grouped.set(item.targetId, {
      targetId: item.targetId,
      assetId,
      url,
      ...(altText ? { altText } : {}),
    });
  }

  return grouped;
}

export function isSourceAppliedImageTargetId(
  value: string | null | undefined
): value is WillardSourceAppliedImageTargetId {
  return SOURCE_APPLIED_IMAGE_TARGET_IDS.includes(
    value as WillardSourceAppliedImageTargetId
  );
}

function buildOverrideEntry(override: WillardGeneratedImageOverride): string {
  const lines = [
    `  ${JSON.stringify(override.targetId)}: {`,
    `    targetId: ${JSON.stringify(override.targetId)},`,
    `    assetId: ${JSON.stringify(override.assetId)},`,
    `    url: ${JSON.stringify(override.url)},`,
  ];

  if (override.altText) {
    lines.push(`    altText: ${JSON.stringify(override.altText)},`);
  }

  lines.push("  }");
  return lines.join("\n");
}

function normalizeModuleString(value: string): string {
  return typeof value === "string" ? value.replace(/[\r\n]+/g, " ").trim() : "";
}
