import { KIND_FIELD_DEFAULTS } from "@/lib/dev/style-lab-defaults";
import {
  TARGET_TO_KIND,
  isStyleTargetId,
  type StyleTargetId,
  type StyleTargetKind,
} from "@/lib/dev/style-lab-inspect";

export const WILLARD_GENERATED_FILE_RELATIVE_PATH = "app/the-feed/willard.generated.css";

const GENERATED_HEADER = `/*
 * This file is generated by /willard from a local Apply action.
 * It is the reviewable source-of-truth override layer for feed-related styles.
 * Manual edits may be overwritten the next time Apply is used.
 */`;

export function buildGeneratedWillardCss(variables: Record<string, string>): string {
  const css = buildTargetStylesheet(variables);

  if (!css.trim()) {
    return `${GENERATED_HEADER}\n\n/* No applied Willard overrides yet. */\n`;
  }

  return `${GENERATED_HEADER}\n\n${css}`;
}

export function buildTargetStylesheet(variables: Record<string, string>): string {
  const targetFields = collectMeaningfulTargetFields(variables);

  return Array.from(targetFields.entries())
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([targetId, fields]) => {
      const kind = TARGET_TO_KIND[targetId as StyleTargetId];
      const declarations = buildDeclarations(kind, fields);

      if (declarations.length === 0) {
        return "";
      }

      return `[data-style-target="${targetId}"] {\n${declarations.join("\n")}\n}`;
    })
    .filter(Boolean)
    .join("\n\n")
    .trimEnd() + (targetFields.size > 0 ? "\n" : "");
}

function collectMeaningfulTargetFields(
  variables: Record<string, string>
): Map<StyleTargetId, Record<string, string>> {
  const grouped = new Map<StyleTargetId, Record<string, string>>();

  for (const [rawKey, rawValue] of Object.entries(variables)) {
    const separatorIndex = rawKey.indexOf("__");
    if (separatorIndex === -1) {
      continue;
    }

    const targetId = rawKey.slice(0, separatorIndex);
    const field = rawKey.slice(separatorIndex + 2);

    if (!isStyleTargetId(targetId)) {
      continue;
    }

    const value = normalizeCssValue(rawValue);
    if (!value) {
      continue;
    }

    const kind = TARGET_TO_KIND[targetId];
    const kindDefaults = KIND_FIELD_DEFAULTS[kind] as Record<string, string>;
    if (kindDefaults[field] === value) {
      continue;
    }

    const existing = grouped.get(targetId) ?? {};
    existing[field] = value;
    grouped.set(targetId, existing);
  }

  return grouped;
}

function normalizeCssValue(value: string): string {
  return value.replace(/[\r\n]+/g, " ").trim();
}

function buildDeclarations(kind: StyleTargetKind, fields: Record<string, string>): string[] {
  const declarations: string[] = [];
  const getValue = (key: string) => fields[key];

  if (kind === "text") {
    if (getValue("font-family")) declarations.push(`  font-family: ${getValue("font-family")} !important;`);
    if (getValue("font-size")) declarations.push(`  font-size: ${getValue("font-size")} !important;`);
    if (getValue("font-weight")) declarations.push(`  font-weight: ${getValue("font-weight")} !important;`);
    if (getValue("line-height")) declarations.push(`  line-height: ${getValue("line-height")} !important;`);
    if (getValue("letter-spacing")) declarations.push(`  letter-spacing: ${getValue("letter-spacing")} !important;`);
    if (getValue("text-transform")) declarations.push(`  text-transform: ${getValue("text-transform")} !important;`);
    if (getValue("color")) declarations.push(`  color: ${getValue("color")} !important;`);
    if (getValue("text-align")) declarations.push(`  text-align: ${getValue("text-align")} !important;`);
    return declarations;
  }

  if (kind === "image") {
    if (getValue("width")) declarations.push(`  width: ${getValue("width")} !important;`);
    if (getValue("max-width")) declarations.push(`  max-width: ${getValue("max-width")} !important;`);
    if (getValue("opacity")) declarations.push(`  opacity: ${getValue("opacity")} !important;`);
    if (getValue("border-radius")) declarations.push(`  border-radius: ${getValue("border-radius")} !important;`);
    if (getValue("border-width") || getValue("border-color")) {
      declarations.push("  border-style: solid !important;");
      if (getValue("border-width")) declarations.push(`  border-width: ${getValue("border-width")} !important;`);
      if (getValue("border-color")) declarations.push(`  border-color: ${getValue("border-color")} !important;`);
    }
    if (getValue("box-shadow")) declarations.push(`  box-shadow: ${getValue("box-shadow")} !important;`);
    if (getValue("x-offset") || getValue("y-offset") || getValue("rotation")) {
      const xOffset = getValue("x-offset") ?? "0px";
      const yOffset = getValue("y-offset") ?? "0px";
      const rotation = getValue("rotation") ?? "0deg";
      declarations.push(`  transform: translate(${xOffset}, ${yOffset}) rotate(${rotation}) !important;`);
    }
    return declarations;
  }

  if (kind === "button") {
    if (getValue("font-family")) declarations.push(`  font-family: ${getValue("font-family")} !important;`);
    if (getValue("font-size")) declarations.push(`  font-size: ${getValue("font-size")} !important;`);
    if (getValue("font-weight")) declarations.push(`  font-weight: ${getValue("font-weight")} !important;`);
    if (getValue("text-color")) declarations.push(`  color: ${getValue("text-color")} !important;`);
    if (getValue("background-color")) declarations.push(`  background: ${getValue("background-color")} !important;`);
    if (getValue("border-width") || getValue("border-color")) {
      declarations.push("  border-style: solid !important;");
      if (getValue("border-width")) declarations.push(`  border-width: ${getValue("border-width")} !important;`);
      if (getValue("border-color")) declarations.push(`  border-color: ${getValue("border-color")} !important;`);
    }
    if (getValue("border-radius")) declarations.push(`  border-radius: ${getValue("border-radius")} !important;`);
    if (getValue("padding-x") || getValue("padding-y")) {
      const paddingY = getValue("padding-y") ?? "0px";
      const paddingX = getValue("padding-x") ?? "0px";
      declarations.push(`  padding: ${paddingY} ${paddingX} !important;`);
    }
    if (getValue("box-shadow")) declarations.push(`  box-shadow: ${getValue("box-shadow")} !important;`);
    return declarations;
  }

  if (getValue("background-color")) declarations.push(`  background: ${getValue("background-color")} !important;`);
  if (getValue("border-width") || getValue("border-color")) {
    declarations.push("  border-style: solid !important;");
    if (getValue("border-width")) declarations.push(`  border-width: ${getValue("border-width")} !important;`);
    if (getValue("border-color")) declarations.push(`  border-color: ${getValue("border-color")} !important;`);
  }
  if (getValue("border-radius")) declarations.push(`  border-radius: ${getValue("border-radius")} !important;`);
  if (getValue("max-width")) declarations.push(`  max-width: ${getValue("max-width")} !important;`);
  if (getValue("margin-x-mode") === "auto") {
    declarations.push("  margin-left: auto !important;");
    declarations.push("  margin-right: auto !important;");
  } else if (getValue("margin-x")) {
    declarations.push(`  margin-left: ${getValue("margin-x")} !important;`);
    declarations.push(`  margin-right: ${getValue("margin-x")} !important;`);
  }
  if (getValue("padding-x")) declarations.push(`  padding-left: ${getValue("padding-x")} !important;`);
  if (getValue("padding-x")) declarations.push(`  padding-right: ${getValue("padding-x")} !important;`);
  if (getValue("padding-y")) declarations.push(`  padding-top: ${getValue("padding-y")} !important;`);
  if (getValue("padding-y")) declarations.push(`  padding-bottom: ${getValue("padding-y")} !important;`);
  if (getValue("padding")) declarations.push(`  padding: ${getValue("padding")} !important;`);
  if (getValue("shadow")) declarations.push(`  box-shadow: ${getValue("shadow")} !important;`);
  if (getValue("opacity")) declarations.push(`  opacity: ${getValue("opacity")} !important;`);

  return declarations;
}
