/*
 * This file is generated by /willard from a local Apply action.
 * It is the reviewable source-of-truth override layer for feed-related image replacements.
 * Manual edits may be overwritten the next time Apply is used.
 */

import type {
  WillardGeneratedImageOverride,
  WillardSourceAppliedImageTargetId,
} from "@/lib/dev/style-lab-images";

export const WILLARD_IMAGE_OVERRIDES: Partial<
  Record<WillardSourceAppliedImageTargetId, WillardGeneratedImageOverride>
> = {};
